### ISSUE TITLE
move _LD_LIBRARY_PATH special casing out to --setenv

### ISSUE THREAD

**Issue by cgwalters** [alexlarsson/bubblewrap#5]
We could require the caller to call setenv() early on in their code, but it would seem more general to just expose e.g.:

`bubblewrap --setenv LD_LIBRARY_PATH "$(LD_LIBRARY_PATH)"`

**Comment by alexlarsson** [comment]
You can't call setenv() in the parent, because execing a setuid helper clears LD_LIBRARY_PATH. However, yes, a --setenv would work too.

**Comment by alexlarsson** [comment]
master has --setenv
